trigger:
  - master

stages:
  - stage: deploy
    displayName: deploy:latest
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: latest
        pool:
          vmImage: "ubuntu-latest"
        environment: latest
        variables:
          - group: shared
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: templates/deploy.prepare.yml
                - script: bump2version build
                  displayName: 'bump build version'
                - script: python setup.py sdist bdist_wheel
                  displayName: 'Generate package'
                - task: TwineAuthenticate@1
                  inputs:
                    artifactFeed: 'proofdockio'
                - script: python -m twine upload --repository proofdockio --config-file $(PYPIRC_PATH) dist/*
                  displayName: 'Upload package to test PyPI'
                - template: templates/deploy.commit.yml